# Generated by Django 5.2.14 on 2026-07-09 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cage', models.CharField(max_length=100)),
                ('cplace', models.CharField(max_length=100)),
                ('cemail', models.CharField(max_length=100)),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('tage', models.IntegerField()),
                ('tplace', models.CharField(max_length=100)),
                ('temail', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('date', models.DateTimeField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Dietplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dietplan', models.TextField()),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
    ]
