# Generated by Django 5.2.14 on 2026-07-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.FileField(default='A1.png', upload_to=''),
            preserve_default=False,
        ),
    ]
