# Generated by Django 5.2.14 on 2026-07-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trainer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
