# Generated by Django 5.2.14 on 2026-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trainer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
