# Generated by Django 5.2.14 on 2026-07-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_client_status_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='Price',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premium',
            name='features',
            field=models.CharField(default='premium', max_length=100),
            preserve_default=False,
        ),
    ]
