# Generated by Django 5.2.14 on 2026-07-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_premium_price_premium_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('DOR', models.DateField()),
                ('EXPD', models.DateField()),
                ('Price', models.IntegerField()),
                ('features', models.CharField(max_length=100)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
