# Generated by Django 5.2.14 on 2026-07-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_premiummembership_delete_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiummembership',
            name='features',
        ),
    ]
