# Generated by Django 5.2.14 on 2026-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_premiummembership_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
