# Generated by Django 5.2.14 on 2026-07-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_premiumvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumvideo',
            name='category',
        ),
    ]
