# Generated by Django 5.2.14 on 2026-07-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_premiumvideo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumvideo',
            name='CLIENT',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
            preserve_default=False,
        ),
    ]
