# Generated by Django 5.2.14 on 2026-07-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_premiumvideo_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumvideo',
            name='CLIENT',
        ),
    ]
